### ISSUE TITLE
gnomonicus version

### ISSUE THREAD

**Issue by alantsangmb** [oxfordmmm/gnomonicus#27]
Hello, @JeremyWesthead @philipwfowler  
I have trouble determining the version of the gnomonicus that I am currently using.
Could you please let me know how I can determine the version of gnomonicus and if there is a command that I can use to check this information?
Thank you in advance for your time.

**Comment by philipwfowler** [comment]
Hi @alantsangmb , glad to hear you are trying out our code. It is under very active development at the moment and I notice that we don't have a way of reporting the release version via a command line flag (`--version`) as one might expect. Is that what you mean? Out of interest what are you are using it for?

**Comment by alantsangmb** [comment]
Thank you for developing this incredibly useful tool. I am currently utilizing gnomonicus to predict drug susceptibility. I am aware that it is still under development and subject to periodic updates. Therefore, I would greatly appreciate if I could obtain information regarding the specific version I used from a command line flag (--version) for traceability purposes.

**Comment by alantsangmb** [comment]
In the meantime, I have discovered that I can find the version information from the docker image overlay directory. Therefore, I am now closing this issue. Thank you so much.

**Comment by JeremyWesthead** [comment]
Hi,
Sorry, I completely forgot to add a `--version` flag to the CLI - it will be added in future. For now, other than the docker version, you should be able to see the version in a few other places:
1. Programmatically via Python - `import gnomonicus` then `print(gnomonicus.__version__)`
  - This could be used as a 1 line bash: `python3 -c "import gnomonicus;print(gnomonicus.__version__)"`
2. Within the `meta` block of the `json` output
3. Via pip: `pip show gnomonicus`

**Comment by alantsangmb** [comment]
Thank you so much indeed.
