### ISSUE TITLE
tuberculosis amr catalogues 

### ISSUE THREAD

**Issue by alantsangmb** [oxfordmmm/gnomonicus#51]
WHO has issued a update of the “Catalogue of mutations in Mycobacterium tuberculosis complex and their association with drug resistance”. Will the catalogue file be updated accordingly? Thank you so much.

**Comment by alantsangmb** [comment]
Hello, I was wondering if there have been any recent developments regarding the addition of the new catalogue to the repo. I apologize if I overlooked any updates or changes. Thank you.

**Comment by JeremyWesthead** [comment]
Hi, sorry it's taken a while for us to validate that this works as expected with some new kinds of rules, but it should be available now https://github.com/oxfordmmm/tuberculosis_amr_catalogues/blob/public/catalogues/NC_000962.3/NC_000962.3_WHO-UCN-TB-2023.5_v2.0_GARC1_RFUS.csv
